version: "3"

networks:
  backend:
    driver: bridge

services:
  neo4j:
    container_name: ${DOCKER_PREFIX:-ig}-neo4j
    image: neo4j:4.0
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-iGeorgia}
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/conf:/conf
      - ./data/neo4j/import:/import
      - ./data/neo4j/logs:/logs
      - ./data/neo4j/plugins:/plugins
    networks:
      - backend
